all: country_test.o date_test.o description_test.o password_test.o city_test.o code_test.o email_test.o idiom_test.o name_test.o grade_test.o

country_test.o: country_test.cpp
	g++ -std=c++17 -Wall -c country_test.cpp

date_test.o: date_test.cpp
	g++ -std=c++17 -Wall -c date_test.cpp

description_test.o: description_test.cpp
	g++ -std=c++17 -Wall -c description_test.cpp

password_test.o: password_test.cpp
	g++ -std=c++17 -Wall -c password_test.cpp

city_test.o: city_test.cpp
	g++ -std=c++17 -Wall -c city_test.cpp

code_test.o: code_test.cpp
	g++ -std=c++17 -Wall -c code_test.cpp

email_test.o: email_test.cpp
	g++ -std=c++17 -Wall -c email_test.cpp

idiom_test.o: idiom_test.cpp
	g++ -std=c++17 -Wall -c idiom_test.cpp

name_test.o: name_test.cpp
	g++ -std=c++17 -Wall -c name_test.cpp

grade_test.o: grade_test.cpp
	g++ -std=c++17 -Wall -c grade_test.cpp

clean:
	rm -rf *.o *.exe
