all: review.o accommodation.o user.o

review.o: review.cpp review.hpp
	g++ -std=c++17 -Wall -c review.cpp

accommodation.o: accommodation.cpp accommodation.hpp
	g++ -std=c++17 -Wall -c accommodation.cpp

user.o: user.cpp user.hpp
	g++ -std=c++17 -Wall -c user.cpp
