all: accommodation_test.o # review_test.o user_test.o

accommodation_test.o: accommodation_test.cpp accommodation_test.hpp
	g++ -std=c++17 -Wall -c accommodation_test.cpp

review_test.o: review_test.cpp review_test.hpp
	g++ -std=c++17 -Wall -c review_test.cpp

user_test.o: user_test.cpp user_test.hpp
	g++ -std=c++17 -Wall -c user_test.cpp
